runtime: python39

env_variables:
  PORT: 8080
  GCLOUD_STORAGE_BUCKET: "chatapplication-983c8-models"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20

entrypoint: gunicorn -b :$PORT main:app --timeout 900 --workers 1 --worker-class sync

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
